### ISSUE TITLE
考虑加一个最近查询记录，可以用来复习背单词

### ISSUE THREAD

**Issue by wensonsmith** [wensonsmith/YoudaoTranslate#10]
之前看过一个 workflow , 不仅可以查单词，还可以把单词加入生词本，很强大也很复杂。

转过念头一想，我们查的不就是因为我们不会嘛，把查询记录列出来就基本等于要复习的内容了

我真是太机智了 👍 

如果复习一遍还是不行，那还是用纸和笔多写几遍吧 ：）

- [x] 输入 `yd *` 的时候列出最近查询的 10 个单词, 用来空闲时间回顾复习。

**Comment by Elvin1993** [comment]
这个功能做了吗 我的小哥哥。

**Comment by wensonsmith** [comment]
还没有。。。最近拖延症严重。  争取下周把这个功能上去  = =!

**Comment by wensonsmith** [comment]
完成进度 70%

**Comment by wensonsmith** [comment]
拖了三个月 😅  可算完成了！

请更新 2.1.0 版本！ 详情请查看 README
