### ISSUE TITLE
能否转移到LaunchBar的Action里？

### ISSUE THREAD

**Issue by zhuqh93** [wensonsmith/YoudaoTranslate#11]
@wensonsmith 你好~首先很感谢作者的无私奉献，制作出这么方便的workflow；现在来说说我的情况：
我之前一直在用Alfred，还买了永久升级的license（忘了叫什么..），后来用了LaunchBar就放弃了Alfred（原因就不说了）。用Alfred的时候第一个workflow就是你的这个有道翻译，直到现在也在用（Alfred只用来查词）。可是LaunchBar没有相关的action（跟workflow一样的作用），所以想问问作者能否制作一个LaunchBar的版本，相信不止我一个用LaunchBar的人在期待着你的答复！

**Comment by wensonsmith** [comment]
我得找一下 LaunchBar 的开发文档，我看他写着支持 `Scriptable Actions` , 所以应该是可以转移的。

待到周末我看一下。

**Comment by wensonsmith** [comment]
2020 年了，弃了 LaunchBar 这个坑了
