### ISSUE TITLE
Passing output '' to Script Filter

### ISSUE THREAD

**Issue by shenguanjiejie** [wensonsmith/YoudaoTranslate#134]
Alfred5.0.6
macOS 12.0.1
权限全都开了, 不是权限问题
重装试过了没用.
经常会出现这个问题.

快捷键复制文本后翻译, 好像没有复制下来.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/9425605/215384449-ae418f02-feca-4bff-81cb-346ee367f0b2.png">

**Comment by shenguanjiejie** [comment]
好像是忘记勾选Selection in macOS了.

**Comment by yfming93** [comment]
> 好像是忘记勾选Selection in macOS了.

我勾选了也没用呀

**Comment by yfming93** [comment]
Mac系统设置中 搜索  Accessibility 中检查 Alfred 是否已勾选，勾选后还是失效，就点击底部删除重新添加下，我就是这情况失效的

**Comment by shenguanjiejie** [comment]
> Mac系统设置中 搜索 Accessibility 中检查 Alfred 是否已勾选，勾选后还是失效，就点击底部删除重新添加下，我就是这情况失效的

你可以试试把这个插件删除, 然后重新安装, 有时候可以解决.

**Comment by n3taway** [comment]
Alfred4.6.3
macOS 13.5

也是Selection in macOS不生效。
隐私与安全性-辅助功能 将Alfred删除再添加就好了。
