### ISSUE TITLE
翻译过快导致有道api支付价格高昂

### ISSUE THREAD

**Issue by AldousShou** [wensonsmith/YoudaoTranslate#136]
希望在对api post之前有一个等待时间，对于我而言，我习惯在采用输入的方式来进行翻译，根据其反馈，我感觉可能是每次输入都进行了一个提交。**我希望能在发起提交之前进行一个小段的等待时间**，确认用户不再输入后再进行提交。

**Comment by bowencool** [comment]
确实，加个 debounce 是常规操作

**Comment by bowencool** [comment]
> 确实，加个 debounce 是常规操作

我打开debug看了下，是有 debounce 效果的，应该是 debounce 的阈值设置低了

**Comment by Medivh-z** [comment]
> > 确实，加个 debounce 是常规操作
> 
> 我打开debug看了下，是有 debounce 效果的，应该是 debounce 的阈值设置低了

现在有道api道频次有限制了。导致长一点的单词键盘输入完成后直接「访问频次受限」。

**Comment by bowencool** [comment]
刚才又看了下，在这里可以修改阈值，可以尝试改大点：
<img width="814" alt="image" src="https://user-images.githubusercontent.com/20217146/221508413-cd19acbd-29f9-4f83-a381-4340647475fb.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/20217146/221508496-4a5874c5-2e0d-4871-9578-5b6220d27edd.png">
