### ISSUE TITLE
Add extra proxy settings

### ISSUE THREAD

**Issue by syhily** [wensonsmith/YoudaoTranslate#14]
My business network is not exposed to public directly. Every request need to be pass to a inner http proxy. So a upstream proxy setting function would help me a lot.

**Comment by wensonsmith** [comment]
Try this 

![image](https://user-images.githubusercontent.com/2544185/31643373-cf7b9604-b2b5-11e7-92ee-99fcad1b0cd4.png)

**Comment by syhily** [comment]
![image](https://user-images.githubusercontent.com/1761698/31645605-9acd4e5e-b2c2-11e7-9b65-61936840687e.png)

Tks, but this doesn't work.

**Comment by jtr109** [comment]
Which mode is your SS set? You could try to use Global Mode. If it works, you should add the `openapi.youdao.com` into your PAC file.

**Comment by syhily** [comment]
@jtr109 I use `ss-local` command line, and expose the http proxy by using privoxy.
So the `http://127.0.0.1:1084` is a inner proxy for myself.

No SS client, no pac file, no Global Mode.

**Comment by jtr109** [comment]
Well. Maybe you are right. The request seems to be called from [the php code](https://github.com/wensonsmith/YoudaoTranslate/blob/dbbdc659f6a9e77b0e8f82cce1dd8f828847d79b/src/YoudaoTranslate.php#L184) instead of Alfred.
If so, an proxy need be added to solve your issue.

**Comment by syhily** [comment]
The youdao api is called by php cURL, so we need to add extra option on here?

https://github.com/wensonsmith/YoudaoTranslate/blob/master/src/YoudaoTranslate.php#L43

**Comment by wensonsmith** [comment]
请参考 #30  自行进行修改
