### ISSUE TITLE
yd 结果返回异常,  现在只能返回一行内容了吗? 

### ISSUE THREAD

**Issue by fanlb** [wensonsmith/YoudaoTranslate#151]
我记得 之前 可以返回 示例,  音标 等多行内容 , 不知道从什么时候开始只能返回一行结果, 求解答 !!! 

![image](https://github.com/wensonsmith/YoudaoTranslator/assets/6261608/13142bb8-deea-475c-b97f-857e706a6655)

**Comment by fanlb** [comment]
希望显示多行结果,   @wensonsmith  大佬 是我哪里的权限或配置 漏掉了吗? 

![image](https://github.com/wensonsmith/YoudaoTranslator/assets/6261608/ee559f41-a899-41e2-b9fa-508e21345d42)

**Comment by spacecaps-cao** [comment]
Same here. I guess It is probably caused by changes in Youdao API.
俺也一样，我猜是 有道 API 变了。

**Comment by fanlb** [comment]
昨天翻了翻源码和有道api文档, 确实是api变更了, 以前音标这些额外信息是放到 basic 字段下面的, 最新的版本这个字段不在返回了
