### ISSUE TITLE
发音&网络 改进

### ISSUE THREAD

**Issue by zhuqh93** [wensonsmith/YoudaoTranslate#17]
Hi，
### 发音
能否请作者考虑将结果中的**音标/发音**设置一个快捷键（shift + Enter），或者将**音标/发音**项固定在第一或第二位置（方便快速选择）。
因为在现在的情况下，每个单词的**音标/发音**位置都不固定，而且一般比较靠后（在第四、第五），不方便选取。
### 网络
记得之前用youdao翻译的workflow都比较顺畅（输入单词之后基本上立刻显示结果），但最近重新用上之后发现延迟非常高，起码有2-3秒，体验效果非常差。另外，我一直是在国外，而且网络速度绝对没有问题，会不会是有道API的问题？

Thanks.

**Comment by wensonsmith** [comment]
我刚才测试了时间， 上海电信30M 请求接口时间大约在 160ms
我感觉是这个 Alfred 参数导致的。 之前为了优化请求次数，设置了 delay . 你按我图中设置改一下试试。

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2544185/32979435-36b6d286-cc90-11e7-8da1-324ad1549785.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2544185/32979442-4b17a476-cc90-11e7-934a-64b6d84b46df.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/2544185/32979464-9a3f8b40-cc90-11e7-9862-3b5b77774c32.png">

PS: 发音这个正在按你说的修改

**Comment by zhuqh93** [comment]
@wensonsmith 修改过后效果不明显，依然存在2s左右的delay。
不清楚这是不是个案，需要更多人的反馈。
个人感觉是有道的问题，可能对国外网络不太友好，可是我肯定之前（大概半年前）是没有延迟的。

**Comment by wensonsmith** [comment]
把 delay 去掉之后，我这边挺快的。 基本是秒出了。 

下面这个连接是翻译接口，你打开看看耗时多少。

[有道接口翻译](https://openapi.youdao.com/api?from=auto&to=auto&appKey=2280cdb033304a40&secret=9WmJZbNe9JaYJl8dzzaZbmcYdsf6VJ7c&q=%E4%BD%A0%E5%A5%BD&salt=76821&sign=300e94a5a90bb8f54cc590b948dc7cf5)

**Comment by zhuqh93** [comment]
@wensonsmith 应该就是自身网络的延迟，我打开那个API接口也是差不多2s。

**Comment by wensonsmith** [comment]
现在可以使用 `Command` + `回车` 来发音了 🔈 

下载最新的 Workflow 即可 , Enjoy !
