### ISSUE TITLE
 回车复制当前单词的时候有个 BUG

### ISSUE THREAD

**Issue by fourn** [wensonsmith/YoudaoTranslate#18]
以前回车都能复制到选中的单词，现在回车无论怎样都只能复制到第一个词了~

**Comment by wensonsmith** [comment]
已确认有这个问题，本周末会修复。

**Comment by VincentZhou98** [comment]
除了这个问题之外还有一个问题：
具体的来说分两种情况
1. 英翻中的时候复制的不是中文而是英文，也就是说英文翻译出的大段中文也无法输出
2. 已经提到，即在中翻英的时候只能复制第一个词

希望能够修复~大赞
👏

**Comment by VincentZhou98** [comment]
@wensonsmith 
首先感谢作者的workflow~
我也遇到了复制的bug
1. **英文翻译中文复制的时候，在选择与输入英文相同的单词时，只复制相应的英文单词
而不是相应的中文**
![Uploading Screen Shot 2018-01-03 at 2.03.30 PM.png…]()
如图所示，选择⌘1-⌘4时，复制下来的都是`copy`而不是中文
而复制⌘6-⌘8时显示的单词就是相应的中文解释了

2. **对于中文翻译英文的情况,也是如此**
![Uploading Screen Shot 2018-01-03 at 2.13.15 PM.png…]()

与翻译中文相同的单词只会显示相应的英文单词
不相同的单词会显示相应的英文解释

3. **长句子翻译只会复制出输入进去的句子而不是翻译后的句子**

**Comment by VincentZhou98** [comment]
@wensonsmith 
首先感谢作者的workflow~
我也遇到了复制的bug
1. **英文翻译中文复制的时候，在选择与输入英文相同的单词时，只复制相应的英文单词
而不是相应的中文**

![screen shot 2018-01-03 at 2 03 30 pm](https://user-images.githubusercontent.com/24786426/34510692-2fdbfdf4-f091-11e7-9ff5-efb570552c98.png)

如图所示，选择⌘1-⌘4时，复制下来的都是`copy`而不是中文
而复制⌘6-⌘8时显示的单词就是相应的中文解释了

2. **对于中文翻译英文的情况,也是如此**
![screen shot 2018-01-03 at 2 13 15 pm](https://user-images.githubusercontent.com/24786426/34510701-45cf3766-f091-11e7-87e5-5a11bb197e77.png)

与翻译中文相同的单词只会显示相应的英文单词
不相同的单词会显示相应的英文解释

3. **长句子翻译只会复制出输入进去的句子而不是翻译后的句子**

**Comment by WangGuibin** [comment]
这个bug修复了没 为啥每次回车都是第一行的单词啊  我光标有移动到自己需要选择的当前行啊

**Comment by fourn** [comment]
忍不了，我自己重新写了一个在用ರ_ರ

**Comment by zthxxx** [comment]
@wensonsmith 

翻译复制问题在这个 [PR#48](https://github.com/wensonsmith/YoudaoTranslate/pull/48) 中修复了，麻烦作者 merge 一下

**Comment by zthxxx** [comment]
related #50

**Comment by wensonsmith** [comment]
已经修复，请下载 [v2.3.0 版本](https://github.com/wensonsmith/YoudaoTranslate/releases/download/v2.3.0/Youdao.Translate.zip)
