### ISSUE TITLE
关于配置和升级的两个建议

### ISSUE THREAD

**Issue by mpco** [wensonsmith/YoudaoTranslate#19]
1. 实现Workflow的自动更新：当作者更新Github后，使用者的版本自动更新。可参考：https://alfredworkflow.readthedocs.io/en/latest/user-manual/update.html
2. 将应用(appKey)和密钥(secret)放在Workflow Environment Variables中，可以更方便的进行设置和导出控制。可参考：https://www.alfredapp.com/help/workflows/advanced/variables/

非常感谢作者的这个Workflow。

**Comment by jijiucheng** [comment]
这个 appKey 必须要 自己申请吗？

**Comment by wensonsmith** [comment]
2020 年更新 第二点已经实现， 第一点快了

**Comment by wensonsmith** [comment]
v2.4.0 可以了

![update](https://github.com/wensonsmith/YoudaoTranslate/raw/master/screenshot/update.png)
