### ISSUE TITLE
有道API报超过频率限制了 

### ISSUE THREAD

**Issue by chxj1992** [wensonsmith/YoudaoTranslate#2]
http://fanyi.youdao.com/openapi?path=data-mode 

哥们儿，给他们发给邮件吧 。。。

**Comment by wensonsmith** [comment]
好的，看样子用这个workflow的人越来越多了啊···
我发个邮件申请一下， 看看有道那边能不能给力

**Comment by wensonsmith** [comment]
邮件已经发送，等待有道回馈

**Comment by chxj1992** [comment]
是啊，1小时1000次的频率都超了，挺屌的，哈哈！

**Comment by wensonsmith** [comment]
扑街。。

![image](https://cloud.githubusercontent.com/assets/2544185/13734035/b42a74f2-e9d4-11e5-96e7-f5919676c65c.png)

下一步想的是，多申请几个API, 然后程序里随机调用。。。我就是这么鸡贼  [dogge]

**Comment by chxj1992** [comment]
哈哈哈，原来对开源项目也是这么小气，说好的 “审核通过后可放宽访问限制”  😂

**Comment by ericwang24** [comment]
我自己去申请了key.

**Comment by chxj1992** [comment]
哈哈 我也是

**Comment by zhaozhiming** [comment]
怪不得最近翻译不了了  

@chxj1992 @ericwang24 请问申请了key之后怎么在Alfred里配置啊？谢谢了

**Comment by zhaozhiming** [comment]
@wensonsmith 期待更新 :+1:

**Comment by chxj1992** [comment]
替换掉 translate.php 中 `keyfrom` 和 `key` 这两项
<img width="931" alt="screen shot 2016-03-16 at 5 02 49 pm" src="https://cloud.githubusercontent.com/assets/1113743/13806938/8b683790-eb99-11e5-87d4-fc369668deb8.png">

**Comment by zhaozhiming** [comment]
@chxj1992 感谢

**Comment by wensonsmith** [comment]
已经改为随机调用啦！
