### ISSUE TITLE
经常出现翻译出错的情况！

### ISSUE THREAD

**Issue by Sunnyhp** [wensonsmith/YoudaoTranslate#23]
系统：Mac OS 13.3
<img width="561" alt="screen shot 2018-03-09 at 10 28 48" src="https://user-images.githubusercontent.com/29660835/37187355-e918bab6-2384-11e8-87e7-9b5590298d34.png">

**Comment by chairuosen** [comment]
有道API换新的了

**Comment by Sunnyhp** [comment]
我这个可以用，但是经常会出现翻译出错的情况，
注：我已按照 README 文档，去有道是智云重新注册了。

**Comment by wensonsmith** [comment]
不好意思，是我欠费了 😂 

最近太忙了，期间发生太多事情了。 

我先付费抗一段时间，后面抽空再更新一版。

**Comment by Sniper1211** [comment]
是不是注册过智云之后就可以呢？

**Comment by elviscai** [comment]
1. 注册有道智云，获得 key。
2. 只用自己的 key，删掉原来的两个。

然后就可以用了。

**Comment by wensonsmith** [comment]
第二个密钥已经欠费了。我本来想充值的。。帐号找不到了。

然后智云的帐号帐号功能有 BUG, 现在还没找回来。 

解决方案参考楼上。
