### ISSUE TITLE
翻译经常报 401

### ISSUE THREAD

**Issue by my9074** [wensonsmith/YoudaoTranslate#25]
> 经常会出现这种情况。

![image](https://user-images.githubusercontent.com/4555635/38228139-69688f12-3734-11e8-9e2f-0dc4ad59b735.png)

**Comment by xieao100** [comment]
401是账户欠费，改成你自己的账户

**Comment by TitorX** [comment]
打开alfred的设置界面

![image](https://user-images.githubusercontent.com/11922492/38600642-79adedea-3d97-11e8-83a1-46ff4cb02012.png)

双击中间的yd图标

![image](https://user-images.githubusercontent.com/11922492/38600709-ab5318ac-3d97-11e8-9d09-891700dbf3da.png)

然后图里的代码，换上自己账户的信息就好了。

百度  有道api  就能找到注册开发者账户的地方了。

**Comment by my9074** [comment]
OK~ thx
