### ISSUE TITLE
出现翻译出错110

### ISSUE THREAD

**Issue by PennyPenny** [wensonsmith/YoudaoTranslate#27]
刚下载的 安装后换成了自己的appkey，翻译的时候报错110， auto2auto这是是啥意思

**Comment by izekers** [comment]
同问

**Comment by wensonsmith** [comment]
两个 appkey 都替换了？ 如果替换了，请检查下替换的格式是不是有问题。

![image](https://user-images.githubusercontent.com/2544185/39986300-dc50b7f0-5793-11e8-9778-b3cd7c452a92.png)

**Comment by izekers** [comment]
问题解决了，你里面默认放置了两个KEY，我只替换了一个。后面把另一个删除了就可以了

**Comment by treedom** [comment]
记住别忘把后面的逗号也删除了.

**Comment by xuanhui1991** [comment]
换成自己的appkey和秘钥，还是有这个错，不知道为啥。。。

**Comment by littlewey** [comment]
> 换成自己的appkey和秘钥，还是有这个错，不知道为啥。。。

我知道了，你的云实例没有绑定翻译服务。

**Comment by wensonsmith** [comment]
2020 年度版本已经有错误详情了。。。
