### ISSUE TITLE
翻译结果上按 Shift 可以直接预览有道网页功能无效

### ISSUE THREAD

**Issue by socekin** [wensonsmith/YoudaoTranslate#28]
如题，按了shift没有反应

**Comment by linzehui** [comment]
可能你没有在Alfred中选择使用shift预览
![image](https://user-images.githubusercontent.com/16056955/39983812-8a581040-578b-11e8-857a-aca495662818.png)

你可以使用 command+Y 来预览

**Comment by treedom** [comment]
按照linzehui操作出来一个界面需要再次"open in chrome"以后再打开

**Comment by wensonsmith** [comment]
按 Shift 就是直接使用 QuickLook 进行网页预览而不需要打开浏览器。 

这个插件现在还不支持直接打开浏览器的。

**Comment by aolivine** [comment]
我也是这个情况,不知道如何解决.

**Comment by ikakaxi** [comment]
我也无效，而且我的页面没有linzehui的选项
![image](https://user-images.githubusercontent.com/6301454/69488525-5b289380-0ea5-11ea-8f8d-72ed5420eb1c.png)

**Comment by wensonsmith** [comment]
![image](https://user-images.githubusercontent.com/2544185/73951133-1060d880-4938-11ea-9f0d-2b259b1435ba.png)
