### ISSUE TITLE
翻译报错 {"errorCode":"205","l":"auto2auto"}

### ISSUE THREAD

**Issue by colorwin** [wensonsmith/YoudaoTranslate#31]
经常出现报错 `{"errorCode":"205","l":"auto2auto"}`
尝试过去申请有道智云，但是没发现有 secret, 直接填 appKey 在 `$keys = []` 中，问题没有解决。

**Comment by hesj** [comment]
我也遇到了该问题

**Comment by sandyplus** [comment]
我一直出现错误：`{"errorCode":"401","l":"auto2auto"}`

**Comment by CimXin** [comment]
我也是出现401，准备去注册一个有道智云，发现非要手机号，于是就放弃了🙂

**Comment by greyireland** [comment]
+1

**Comment by g4time** [comment]
![image](https://user-images.githubusercontent.com/10024305/42548667-da2d91d4-84fa-11e8-8480-2f8085b83ee1.png)
注意申请的接入方式选择API，就有应用秘钥啦

**Comment by colorwin** [comment]
@g4time  感谢。
申请[有道智云](https://ai.youdao.com/app_detail.s):  我的应用，创建应用，名字描述随意填，申请的接入方式选择API，勾选语音和文本翻译，然后在我的应用点击蓝色的应用名称，就看到应用id（appkey）和应用密钥（secret）。然后去Alfred的workflow那里，选YoudaoTranslate，双击script filter，替换原来的appkey和secret，可以删掉多余的一条，就好了。
