### ISSUE TITLE
更换快捷键

### ISSUE THREAD

**Issue by bensonzhe** [wensonsmith/YoudaoTranslate#33]
请教一下如何将 shift 预览网页的功能更换为其他按键，因为和输入法中英切换冲突，感觉不太方便，谢谢

**Comment by wensonsmith** [comment]
![image](https://user-images.githubusercontent.com/2544185/42010689-75900384-7ac2-11e8-88df-ba563be2b318.png)

可以取消 Shift 预览，使用 Command + Y 

这个是 Alfred 的设置， 不受插件控制。
