### ISSUE TITLE
alfred3.6不能按shift预览，enter按键复制的是输入的英文，不是选择的翻译内容

### ISSUE THREAD

**Issue by zhangyongbo** [wensonsmith/YoudaoTranslate#35]
alfred3.6不能按shift预览；
enter按键复制的是输入的英文，不是选择的翻译内容；

**Comment by xiebruce** [comment]
@zhangyongbo 
1、Features->File Search->Previews，看看QuickLook那个勾是不是被你去掉了？我也是3.6，但我可以预览（另外我想问你个问题：alfred到底是在哪里看版本的？找遍了也找不到有『关于』之类的菜单）
2、Enter键复制的确实是输入的英文而不是当前行的结果

**Comment by zhangyongbo** [comment]
@xiebruce update页面的左上角有版本号，Previews的预览是选中的，点空格后出现了个页面，只是没有网页内容，而是一个Safari图标页面。我现在已经不用这个workflow了推荐这个翻译：https://github.com/liszd/whyliam.workflows.youdao

**Comment by zthxxx** [comment]
@zhangyongbo  翻译复制问题在这个 [PR#48](https://github.com/wensonsmith/YoudaoTranslate/pull/48) 中修复了，但是不知道作者什么时候会 merge

**Comment by wensonsmith** [comment]
已经在 v2.3.0 修复
