### ISSUE TITLE
双击option键盘没有效果

### ISSUE THREAD

**Issue by mrxu0** [wensonsmith/YoudaoTranslate#37]

**Comment by RedApricot** [comment]
同没有效果。。 求方法。。谢谢。

**Comment by HY0606** [comment]
设置了hotkey也没用

**Comment by HY0606** [comment]
在设置了hotkey之后  重启下应用就好了

**Comment by dawnmy** [comment]
我的也是这样，而且重新设置，重启都无效

**Comment by ikakaxi** [comment]
我也是双击没效果

**Comment by ikakaxi** [comment]
可以了，在这里
![image](https://user-images.githubusercontent.com/6301454/69488456-76df6a00-0ea4-11ea-9da0-b96ebe15ef95.png)
我已经设置好了，刚下载下来是没有设置的，自己双击HotKey，然后选择你想要的快捷键，然后保存就可以了，然后选一个单词按下你刚才设置的快捷键，会说需要什么权限，然后在
![image](https://user-images.githubusercontent.com/6301454/69488486-bf972300-0ea4-11ea-84d2-d023a1e0920a.png)
这里添加即可，不需要重启任何东西

**Comment by zthxxx** [comment]
在 #52 中已经添加了默认的 Double ⌥ 快捷键

![image](https://user-images.githubusercontent.com/15135943/73819963-a0652c00-482b-11ea-82fb-5611ca475aa4.png)
