### ISSUE TITLE
用不了，报errcode 401

### ISSUE THREAD

**Issue by amghost** [wensonsmith/YoudaoTranslate#38]

**Comment by chickenren** [comment]
同样报401

**Comment by wangzhenxyz1** [comment]
四、 配置KEYS

2017年9月3日更新 由于有道翻译 api 迁移到了有道智云，所以大家需要去有道智云进行注册然后创建应用了。步骤如下：
注册有道智云帐号
创建一个自然语言翻译服务
创建一个应用并绑定第二步创建的服务
这样就可以获得应用(appKey)和密钥(secret)了

**Comment by WilliamMoon** [comment]
> 四、 配置KEYS
> 
> 2017年9月3日更新 由于有道翻译 api 迁移到了有道智云，所以大家需要去有道智云进行注册然后创建应用了。步骤如下：
> 注册有道智云帐号
> 创建一个自然语言翻译服务
> 创建一个应用并绑定第二步创建的服务
> 这样就可以获得应用(appKey)和密钥(secret)了

我是按照如上流程操作再使用的，但是报错`{"errorCode":"401","l":"auto2auto"}`。
极易复现，输入任意一个字母可能报错，增删字母可能报错，报错概率比不报错概率大。可能先不报错，增加再删除一个字母变为原来的单词又报错，再次增加再删除一个字母又不报错，再次增加再删除一个字母又报错，类似的同一个单词同一次使用里先报错再不报错再报错再不报错也出现过。
appKey和secret没问题，因为不报错的时候，在有道智云里可以看到“自然语言翻译”服务调用次数+1。

**Comment by 631068264** [comment]
@WilliamMoon  你要删除或注释掉默认的appKey和secret，只留下自己的

**Comment by hzfmer** [comment]
@amghost  只留下自己的key就可以。
@631068264  所以用了一段时间就要向有道缴费对吗？

**Comment by radarFudan** [comment]
我测试了一下，删掉默认的，留下自己的就可以用了，但是不知道之后费用怎么样，不管怎么样，还是蛮方便的吧～
