### ISSUE TITLE
翻译长句预览格式问题

### ISSUE THREAD

**Issue by itswenb** [wensonsmith/YoudaoTranslate#43]

**Comment by itswenb** [comment]
翻译英文长句,预览的时候显示字符分隔是用"+"而不是空格

**Comment by zthxxx** [comment]
不是开箱即用，需要自己申请有道云账号

[README - 四、 配置KEYS](https://github.com/wensonsmith/YoudaoTranslate#%E5%9B%9B-%E9%85%8D%E7%BD%AEkeys)

**Comment by wensonsmith** [comment]
请截图示意

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/73948680-41d7a500-4934-11ea-801d-68211607bf87.png)


![image](https://user-images.githubusercontent.com/15135943/73948663-3ab09700-4934-11ea-9845-f67fecccd226.png)

**Comment by wensonsmith** [comment]
已解决， urlencode 会把空格变为 + ，需要使用 rawurlencode
