### ISSUE TITLE
下载安装后直接使用出错。

### ISSUE THREAD

**Issue by chillyond** [wensonsmith/YoudaoTranslate#47]
![image](https://user-images.githubusercontent.com/11400674/61021373-dfd1b400-a3d3-11e9-9e5a-9c035cc6e311.png)

**Comment by zthxxx** [comment]
不是开箱即用，需要自己申请有道云账号

[README - 四、 配置KEYS](https://github.com/wensonsmith/YoudaoTranslate#%E5%9B%9B-%E9%85%8D%E7%BD%AEkeys)

**Comment by chillyond** [comment]
> 不是开箱即用，需要自己申请有道云账号
> 
> [README - 四、 配置KEYS](https://github.com/wensonsmith/YoudaoTranslate#%E5%9B%9B-%E9%85%8D%E7%BD%AEkeys)
嗯，后来我试了一下是可以了。但是最近使用，好像结果列表变成这样了，我记得以前是有很多信息的。
![image](https://user-images.githubusercontent.com/11400674/73632273-2e0f1300-4696-11ea-847d-ec141cc9dc0b.png)

**Comment by zthxxx** [comment]
@chillyond   已在 #52 中修复
