### ISSUE TITLE
貌似在 alfred3中不能用了，前几天还好好的。。

### ISSUE THREAD

**Issue by ahjsrhj** [wensonsmith/YoudaoTranslate#5]
打的 log 如下。。
![2016-11-08 5 09 59](https://cloud.githubusercontent.com/assets/8666955/20093112/513ea098-a5d6-11e6-842c-1826704e4cef.png)

**Comment by wensonsmith** [comment]
我现在用的 Alfred 3 一切正常呀~

看你这个LOG ，感觉是在用 alfred 2 残留的文件夹导致的错误。 用 cleanMyMac 重新卸载安装试试呢？

**Comment by ahjsrhj** [comment]
好了，是我给设了个代理- -结果能用了
