### ISSUE TITLE
cmd + 回车没有声音了

### ISSUE THREAD

**Issue by baozc** [wensonsmith/YoudaoTranslate#50]
升级到catalina后好多软件不能用了，就通过备份降级到mojave了
然后就发现发音突然不能用了，请问这个是什么原因？

**Comment by zthxxx** [comment]
请先在命令行里试试 

```
say mojave -v Samantha
```

有没有声音

**Comment by wensonsmith** [comment]
没有声音和 #53 里的问题有关联

现在为了保证复制到是中文，导致 cmd + 回车 是发的中文音。 系统自带的 say 命令无法发中文

**Comment by zthxxx** [comment]
> 没有声音和 #53 里的问题有关联
> 
> 现在为了保证复制到是中文，导致 cmd + 回车 是发的中文音。 系统自带的 say 命令无法发中文

@wensonsmith  可能并不是，

现在对英文翻译第一项 cmd + 回车 还是发的英文饮，

对中文翻译  cmd + 回车 还是发的也还是英文音

**Comment by wensonsmith** [comment]
对呀，第一项做了特殊处理，和其他项的行为不一致。 

第一项的特殊处理导致第一项复制问题。 

其他项没有处理，导致了 cmd+ 回车 发音的问题

**Comment by zthxxx** [comment]
@baozc  用户麻烦来复现一下 😂

**Comment by baozc** [comment]
1. 在命令行输入`say mojave -v Samantha` ，返回**Open speech channel failed: -241**
2. 现在不管是翻译中文还是英文都是没有声音的

**Comment by baozc** [comment]
@zthxxx 你好，你说这个BUG，我记得好像一直都有，能发声音时就有……

**Comment by zthxxx** [comment]
> @zthxxx 你好，你说这个BUG，我记得好像一直都有，能发声音时就有……

🤣那不是 bug 是 feature

**Comment by baozc** [comment]
> > @zthxxx 你好，你说这个BUG，我记得好像一直都有，能发声音时就有……
> 
> 🤣那不是 bug 是 feature

好吧，原谅我的无知
我刚才看了下say命令，然后试了下我电脑的其它语音播放功能，发现siri和设置里其它的语音播放都不可以用（可以正常使用，但是没有声音），初步怀疑是我电脑的问题，打算明天联系下客服问问

**Comment by zthxxx** [comment]
> > @baozc 用户麻烦来复现一下 😂
> 
> 1. 在命令行输入`say mojave -v Samantha` ，返回**Open speech channel failed: -241**
> 2. 现在不管是翻译中文还是英文都是没有声音的

这样看就是系统降级的问题了 看看系统设置 - 辅助功能 - 语音 - 播放 能不能放出来呢

**Comment by wensonsmith** [comment]
不是 workflow 问题，先关闭了
