### ISSUE TITLE
直接回车无法复制

### ISSUE THREAD

**Issue by Chuhan1112** [wensonsmith/YoudaoTranslate#53]
英文翻译中文，直接回车无法复制翻译后的中文
中文翻译英文，可以
Catalina 10.15.3

**Comment by Chuhan1112** [comment]
<img width="889" alt="截屏2020-02-06下午5 49 02" src="https://user-images.githubusercontent.com/35064712/73925423-ff4ca300-4908-11ea-8976-28ad7b41eeaa.png">
<img width="922" alt="截屏2020-02-06下午5 48 55" src="https://user-images.githubusercontent.com/35064712/73925460-0e335580-4909-11ea-8e7b-df726978b2db.png">

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/73925883-b47f5b00-4909-11ea-8d1b-1b681a264b00.png)

```
n. 远程轰炸机
```

复制结果正常，请问下复现步骤或者录屏？

**Comment by wensonsmith** [comment]
我尝试了一下， 第一个选项无法正常复制

**Comment by zthxxx** [comment]
> 我尝试了一下， 第一个选项无法正常复制

@wensonsmith  @Chuhan1112  使用 `Command + C` 来复制，

这个是有意这么设计的，目的是方便听英语发音

**Comment by zthxxx** [comment]
> > 我尝试了一下， 第一个选项无法正常复制
> 
> @wensonsmith @Chuhan1112 使用 `Command + C` 来复制，
> 
> 这个是有意这么设计的，目的是方便听英语发音

(因为 alfred 的内建通用复制是 ⌘+C)

设计的常用流程是这样：

`有想听发音的单词` -> `选中或者输入到这个 alfred` -> `直接 ⌘+回车 就能听发音`

`如果想复制单词翻译的第一个中文` ->  `⌘+C 复制`

这个特殊点可能需要在 README 里面说明一下 @wensonsmith

**Comment by wensonsmith** [comment]
@zthxxx  

是的，Alfred 里面，` arg` 参数既负责按回车后的复制文本，又负责按住 `⌘ + 回车` 后的发音.

当中文翻译英文时，翻译来的是英文，我们要复制和听的也是英文，所以行为统一没问题

当英文翻译中文时， 翻译过来时中文，我们要复制中文，却想听英文导致的这个问题

**Comment by wensonsmith** [comment]
这里我再想怎么做处理，要保证行为的一致性。

即复制第一项和其他项一致，发音通过判别中英文进行处理。

**Comment by Chuhan1112** [comment]
收到 cmd+c 可以 谢谢

**Comment by wensonsmith** [comment]
重构了发音和复制逻辑，用 mod() 函数比较完美的实现了复制、发音 、cmd+、 alt+ 功能。

请下载 [ v2.3.0 版本 ](https://github.com/wensonsmith/YoudaoTranslate/releases/download/v2.3.0/Youdao.Translate.zip)
