### ISSUE TITLE
大神，你好，能做过谷歌翻译的吗

### ISSUE THREAD

**Issue by songxing10000** [wensonsmith/YoudaoTranslate#6]
感觉谷歌翻译的从简体中文到英文特别实用，因为我也是做开发的，开发时取英文还是很常用的，但是用了百度翻译和有道翻译再用谷歌翻译，感觉还是谷歌翻译好用些，由于本人能力有限希望大神有时间写个谷歌翻译的，或者提供点思路，我也可以研究一下

**Comment by wensonsmith** [comment]
谷歌翻译的话做起来也应该不难，但是最近的话还没有时间去做。

你要是懂的PHP,可以看一下这个源码， workflow.php 是引用的类，很简单。

http://www.alfredworkflow.com/ 来这里找一找，Google 翻译的 workflow 肯定有的
