### ISSUE TITLE
怎么设置快捷键唤出翻译输入框

### ISSUE THREAD

**Issue by qiujie8092916** [wensonsmith/YoudaoTranslate#60]
`⇧ Shift + Space` 直接唤出翻译输入框
怎么设置？？
hotKey只能键入 `^ ⌥ ⇧ ⌘`
<img width="553" alt="截屏2020-04-01 14 10 23" src="https://user-images.githubusercontent.com/18651667/78104897-8f4b2c80-7422-11ea-91e1-17d9aa12e638.png">

 @wensonsmith

**Comment by wensonsmith** [comment]
直接按住 `Shift + Space` 如果不可以的话，是不是与系统中其他快捷键冲突了？

我自己用的是 `Ctrl + space` 


![image](https://user-images.githubusercontent.com/2544185/78334837-0caba400-75bf-11ea-9de1-5a9a8e8d4c8d.png)
