### ISSUE TITLE
双击 option 获取不到 selection 的内容

### ISSUE THREAD

**Issue by jeffreylyg** [wensonsmith/YoudaoTranslate#62]

**Comment by desirelll** [comment]
我也是 

macOS 10.14.6
Alfred 4.0.9
YoudaoTranslate v2.6.0

**Comment by desirelll** [comment]
> 我也是
> 
> macOS 10.14.6
> Alfred 4.0.9
> YoudaoTranslate v2.6.0

我解决了，mac设置-隐私-accessibility去掉Alfred再加回来，然后重启电脑
