### ISSUE TITLE
一直显示正在翻译中

### ISSUE THREAD

**Issue by jackiewillen** [wensonsmith/YoudaoTranslate#65]
![image](https://user-images.githubusercontent.com/7625197/79105751-da126000-7da3-11ea-8a00-70c5b9b6e250.png)

**Comment by RainFung** [comment]
我也是，然后log一直显示
```
Logging Started...
```

**Comment by RainFung** [comment]
我使用的是alfred 4，是不是目前还不支持

**Comment by jackiewillen** [comment]
> 我使用的是alfred 4，是不是目前还不支持

我后来修复了，需要修改代理 proxy,就可以了，因为有的时候是公司的内网，所以不行。

**Comment by RainFung** [comment]
> > 我使用的是alfred 4，是不是目前还不支持
> 
> 我后来修复了，需要修改代理 proxy,就可以了，因为有的时候是公司的内网，所以不行。

您好，我应该跟你是一样的问题， 麻烦能说下具体解决步骤么

**Comment by zhangrg-php** [comment]
catalina : 19E287 
PHP: 7.1.32 
iconv:1.14

显示翻译中，然后出现search

经测试是iconv的问题

打开有道所在的文件夹：

在Alfred中输入al 打开设置，选择workflows 左侧找到”有道“ 右键，open in finder

找到 YoudaoTranslate.php ，53行注释

`// $query = iconv("UTF-8-MAC", "UTF-8", $query);`

**Comment by GeeJoe** [comment]
> > > 我使用的是alfred 4，是不是目前还不支持
> > 
> > 
> > 我后来修复了，需要修改代理 proxy,就可以了，因为有的时候是公司的内网，所以不行。
> 
> 您好，我应该跟你是一样的问题， 麻烦能说下具体解决步骤么

打开 Alfred 的设置页， 在 advanced -> Network 上勾选「Use macOs http proxy settings for scripts」,然后在 MAC 电脑上配置好代理就好了

**Comment by RainFung** [comment]
还是没有解决，哭

**Comment by wensonsmith** [comment]
@RainFung 

![image](https://user-images.githubusercontent.com/2544185/89881786-8b14f400-dbf8-11ea-8baf-23e0551c2635.png)

你打开这个 debug， 随便翻译一个，截图我看看日志

**Comment by RainFung** [comment]
![image](https://user-images.githubusercontent.com/23121539/89971489-ee9d3100-dc8d-11ea-8ca5-20c7c0e58e57.png)

**Comment by RainFung** [comment]
[17:43:16.811] Youdao Translate[Script Filter] Queuing argument '翻译'
[17:43:16.931] Youdao Translate[Script Filter] Script with argv '翻译' finished
[17:43:16.933] Youdao Translate[Script Filter] {"items":[{"arg":"\u7ffb\u8bd1\u51fa\u9519","icon":{"path":"translate.png"},"mods":{"cmd":{"subtitle":"\ud83d\udd0a","arg":null,"valid":true},"alt":{"subtitle":"\ud83d\udd0a","arg":null,"valid":true},"ctrl":{"subtitle":"\ud83d\udcdd \u52a0\u5165\u751f\u8bcd\u672c","arg":"||\u7ffb\u8bd1\u51fa\u9519","valid":true}},"quicklookurl":"http:\/\/youdao.com\/w\/%E7%BF%BB%E8%AF%91","subtitle":"\u7ffb\u8bd1\u5931\u8d25\uff0c\u9519\u8bef\u7801\uff1a","text":{"copy":"\u7ffb\u8bd1\u51fa\u9519"},"title":"\u7ffb\u8bd1\u51fa\u9519","valid":true}]}

**Comment by RainFung** [comment]
显示：翻译出错

**Comment by wensonsmith** [comment]
我把 json 解析出来，看到翻译出错 errorCode 都是空，返回结果是空，说明请求 api 过程有问题。

![image](https://user-images.githubusercontent.com/2544185/90008310-b66a1280-dcce-11ea-8d39-4d04c7794d65.png)

1. 右键 open in terminal
2. vim test.php
3. 把下面代码复制进去，注意要替换其中的 appKey 和 secret

```
<?php

require('YoudaoTranslate.php');

$keys = [
	['appKey' =>'替换为你的应用 ID', 'secret' => '替换为你的应用密钥']
];

$translator = new YoudaoTranslate($keys);
print_r(json_decode($translator->translate('hello')));

?>
```

4. 执行 php test.php 看看输出结果

**Comment by RainFung** [comment]
stdClass Object
(
    [items] => Array
        (
            [0] => stdClass Object
                (
                    [arg] => 翻译出错
                    [icon] => stdClass Object
                        (
                            [path] => translate.png
                        )

                    [mods] => stdClass Object
                        (
                            [cmd] => stdClass Object
                                (
                                    [subtitle] => 🔊
                                    [arg] => 
                                    [valid] => 1
                                )

                            [alt] => stdClass Object
                                (
                                    [subtitle] => 🔊
                                    [arg] => 
                                    [valid] => 1
                                )

                            [ctrl] => stdClass Object
                                (
                                    [subtitle] => 📝 加入生词本
                                    [arg] => ||翻译出错
                                    [valid] => 1
                                )

                        )

                    [quicklookurl] => http://youdao.com/w/hello
                    [subtitle] => 翻译失败，错误码：
                    [text] => stdClass Object
                        (
                            [copy] => 翻译出错
                        )

                    [title] => 翻译出错
                    [valid] => 1
                )

        )

)

**Comment by wensonsmith** [comment]
说明和 Alfred 没关系， 你尝试过 @zhangrg-php 提到的方法了么？

> 在Alfred中输入al 打开设置，选择workflows 左侧找到”有道“ 右键，open in finder
> 
> 找到 YoudaoTranslate.php ，53行注释
> 
> // $query = iconv("UTF-8-MAC", "UTF-8", $query);

**Comment by RainFung** [comment]
试了， 还是不行

**Comment by wensonsmith** [comment]
这是为难我胖虎啊

**Comment by hjijin** [comment]
添价了账号密码那些信息还是提示应用ID无效，并且会自动修改顺序。

**Comment by RainFung** [comment]
是的， 现在就是提示我应用ID无效了

**Comment by ycjcl868** [comment]
+1

**Comment by alarm10086** [comment]
> stdClass Object
> (
> [items] => Array
> (
> [0] => stdClass Object
> (
> [arg] => 翻译出错
> [icon] => stdClass Object
> (
> [path] => translate.png
> )
> 
> ```
>                 [mods] => stdClass Object
>                     (
>                         [cmd] => stdClass Object
>                             (
>                                 [subtitle] => 🔊
>                                 [arg] => 
>                                 [valid] => 1
>                             )
> 
>                         [alt] => stdClass Object
>                             (
>                                 [subtitle] => 🔊
>                                 [arg] => 
>                                 [valid] => 1
>                             )
> 
>                         [ctrl] => stdClass Object
>                             (
>                                 [subtitle] => 📝 加入生词本
>                                 [arg] => ||翻译出错
>                                 [valid] => 1
>                             )
> 
>                     )
> 
>                 [quicklookurl] => http://youdao.com/w/hello
>                 [subtitle] => 翻译失败，错误码：
>                 [text] => stdClass Object
>                     (
>                         [copy] => 翻译出错
>                     )
> 
>                 [title] => 翻译出错
>                 [valid] => 1
>             )
> 
>     )
> ```
> 
> )

我遇到的问题表现结果和你一样（翻译出错，但没错误码）。然后调整了surge 的配置，解决了。
