### ISSUE TITLE
无效的应用ID

### ISSUE THREAD

**Issue by wang-jiyu** [wensonsmith/YoudaoTranslate#66]
![image](https://user-images.githubusercontent.com/20855230/79427181-d1659800-7ff6-11ea-9f7a-91e24e5ed23b.png)

**Comment by lizhaolin09** [comment]
看后面的介绍，要申请有道智云的账号，自己填进去

**Comment by HanderWei** [comment]
@wang-jiyu 这个问题解决了吗？

**Comment by HanderWei** [comment]
```
5. 把变量填入 workflow 右上角的 [X] 点开后的配置框中
```

**Comment by gewuang** [comment]
我就是来问解决了没

**Comment by gewuang** [comment]
搞定了，按照网上的，去掉读取变量，直接静态设置两遍就可以了
![image](https://user-images.githubusercontent.com/20788261/83397102-a5c83100-a42f-11ea-8181-f3d5874b8af9.png)
