### ISSUE TITLE
有道智云密码明文问题

### ISSUE THREAD

**Issue by cuiqiusheng** [wensonsmith/YoudaoTranslate#67]
填写有道智云信息的时候，网易的账号和密码都是明文填写，感觉很不安全，下一版可以考虑一下这个问题吗

**Comment by Yuanwe** [comment]
都是在你电脑里面，为啥不安全了

**Comment by wensonsmith** [comment]
可以考虑存 md5, 但是比较麻烦。反正也是本地应用，代码都是公开的。你登录邮箱的时候就是需要输入密码啊
