### ISSUE TITLE
配置需要用户名和密码的原因是什么？

### ISSUE THREAD

**Issue by lonelygo** [wensonsmith/YoudaoTranslate#71]
配置中已经有了：应用ID appKey, 应用密钥 secret，还需要登陆用户名和密码的原因是什么？

**Comment by zthxxx** [comment]
不用单词本功能就不需要用户名密码

**Comment by lonelygo** [comment]
> 不用单词本功能就不需要用户名密码

嗯，看了一眼源码，是为了保存单词本，不过建议还是不要明文现实了，base64下呗
