### ISSUE TITLE
在线发音似乎是失效的

### ISSUE THREAD

**Issue by haxifang-aircos** [wensonsmith/YoudaoTranslate#73]
这是我第三次尝试引入这个非常好用的插件到 Alfred 4，但是这一次在线发音（command + 回车）没有任何声音，翻译功能是正常的。
Youdao Traanslate : v2.7.1
Mac OS: 10.15.6
![image](https://user-images.githubusercontent.com/61681123/92841209-9e43fb00-f414-11ea-9778-7d1423eb10c8.png)

**Comment by wensonsmith** [comment]
等我我升级到 alfred 4 试一试

**Comment by guotingchaopr** [comment]
v3.8.6 i have same problem
