### ISSUE TITLE
Alfred 3.0 下无法使用，提示无法获取网络

### ISSUE THREAD

**Issue by zzvv** [wensonsmith/YoudaoTranslate#8]
<img width="581" alt="2017-05-13 at 01 34" src="https://cloud.githubusercontent.com/assets/11956161/26009761/cdf88dd2-377c-11e7-85c0-6b548e08f664.png">

RT，之前一直都正常使用，昨天尝试把本机的小飞机替换为Surge 后出现这个异常。
测试了下，貌似所有需要发起API调用的Workflow 均提示这个错误。😳

**Comment by wensonsmith** [comment]
看这个样子是你机器的代理出错了， 不是 alfred 的问题。

**Comment by zzvv** [comment]
Hi， 抱歉再次打扰到您。

```php
  /**
     * 组装请求地址
     * @return String
     */
    private function getQueryUrl($query)
    {
        $api = 'http://fanyi.youdao.com/openapi.do?type=data&doctype=json&version=1.1&';

        $key = $this->keys[array_rand($this->keys)];
        $key['q'] = $query;
        return $api.http_build_query($key);
    }
```
我看了下源文件，其中有这么一段定义请求相关信息的地方。
抱歉不会php，我猜最后句应该是发起请求的。
不知道是否是其中哪个参数可以自定义下发起请求的*ip:port*
alfred 本身的代理我也是有配置的，但不是**127.0.0.1:80**，
所以我猜是不是php中如果没有指定发起HTTP请求的端口，默认就直接走了本机的80端口去请求？

**Comment by wensonsmith** [comment]
你贴出来的函数只是组装了一个地址， 然后是用的 curl 去请求这个地址。 

现在请求这个地址的时候，自动跑到了 127.0.0.1：80 , 说明Surge 已经把代理拿过去了。

alfred 已经走到代理这里了。 我没用过 Surge , 感觉应该是 Surge 规则设置的有问题。 你可以去 Surge 论坛群组里去问一问。

**Comment by zzvv** [comment]
<img width="683" alt="2017-05-28 at 10 15" src="https://cloud.githubusercontent.com/assets/11956161/26525602/c2004e52-438e-11e7-86d6-b1eed43f6d88.png">
找到原因了，如图. 我在勾选了alfred的代理设置后，手贱点开Setting后又手动指定了一个本地代理地址，诸如：0.0.0.0:6197，就全部失效掉。- -
