### ISSUE TITLE
翻译出错

### ISSUE THREAD

**Issue by zm823080538** [wensonsmith/YoudaoTranslate#82]
显示 应用ID无效

**Comment by lyhxiangyang** [comment]
我也出错了 不知道怎么解决

**Comment by Smithjoppa** [comment]
需要在有道云中添加你自己申请的key和secret
<img width="827" alt="image" src="https://user-images.githubusercontent.com/41426528/128668526-ad6bf1a8-d95c-44d2-b585-88400761ca41.png">

**Comment by wensonsmith** [comment]
#94 

后面会完善文档
