### ISSUE TITLE
appkey 和 secret 哪里不对？

### ISSUE THREAD

**Issue by busyrat** [wensonsmith/YoudaoTranslate#84]
![image](https://user-images.githubusercontent.com/20984527/120877056-f9430100-c5e6-11eb-825d-c4a9bfefc585.png)
![image](https://user-images.githubusercontent.com/20984527/120877070-0d86fe00-c5e7-11eb-87cb-9ae6ecd61d2f.png)

**Comment by mgfjx** [comment]
遇到同样的问题，提示应用ID无效

**Comment by mgfjx** [comment]
已解决，必须要输入网易账号才行

**Comment by wensonsmith** [comment]
看样子我需要完善一下文档了。
