### ISSUE TITLE
Unable to run task on macOS 12.0

### ISSUE THREAD

**Issue by LightFocus** [wensonsmith/YoudaoTranslate#85]
When try to use yd on macOS 12.0, it shows the following error
<img width="328" alt="Screen Shot 2021-06-14 at 02 05 06" src="https://user-images.githubusercontent.com/22290740/121817726-a687da00-ccb5-11eb-854e-77557a8f548d.png">

**Comment by Wetoria** [comment]
Same issue

**Comment by JianGuoPaPa** [comment]
希望作者大大能跟进一下呀，是不是引用到的什么系统文件 新系统迁移掉了呀

**Comment by LightFocus** [comment]
I think the problem is that, Alfred uses macOS pre-installed php which is located at /usr/bin/php. With macOS 12, this has been removed. Therefore, when trying to launch app with that path, the error will occur. I don't know how to change the default php path Alfred uses, probably we need an update on Alfred.
<img width="1292" alt="Screen Shot 2021-06-24 at 12 58 16" src="https://user-images.githubusercontent.com/22290740/123205099-dc199800-d4eb-11eb-8912-231f293fb549.png">

**Comment by wensonsmith** [comment]
yes, the pre-installed php has removed in macOS 12 , you need install php by yourself

```
brew install php
```

after install php, change the path to  `/usr/local/bin/php`

**Comment by Wetoria** [comment]
> yes, the pre-installed php has removed in macOS 12 , you need install php by yourself
> 
> ```
> brew install php
> ```
> 
> after install php, change the path to `/usr/local/bin/php`

I'm sorry.

I can't find any solution to set the path. There is no `/usr/local/bin/php` in `language` setting.

Can you tell me how to set it, plz.

**Comment by WeeHong** [comment]
@Wetoria 
Follow this guide.
https://www.jianshu.com/p/c18f1dc2f44b

**Comment by yueyericardo** [comment]
Thanks a lot!

**Comment by Innei** [comment]
> @Wetoria Follow this guide. [jianshu.com/p/c18f1dc2f44b](https://www.jianshu.com/p/c18f1dc2f44b)

`$1` 指传递了一个参数，如果是翻译的话这么传递后面的参数.

`yd Hello world` => 只会传递 `php yd.php Hello` World 就没了

**Comment by wensonsmith** [comment]
用 macOS 的同志，如果没有单词本的需求，用 3.0 吧！

**Comment by fancymax** [comment]
@Innei That can be fixed if you change it to /bin/zsh from /bin/bash.

I still use Alfred 3, so I had to use this workaround solution.
The V3 didn't support Alfred 3.

**Comment by wensonsmith** [comment]
@fancymax 

v3 source code should be compatible with Alfred 3, i use Alfred 4 export the workflow, this may be the problem。

you can git clone the source code, then run `pnpm i && pnpm run build` ,  and put the dist folder files to alfred v3 workflow folder, change the scripts in `Script Filter` block  at the last
