### ISSUE TITLE
配置好后无法运行 "Unable to run task!"

### ISSUE THREAD

**Issue by ZiyunChi** [wensonsmith/YoudaoTranslate#86]
<img width="262" alt="CleanShot 2021-07-14 at 21 08 44@2x" src="https://user-images.githubusercontent.com/59868778/125627413-02249ffb-dcf8-44b6-8d45-f5cbf2fc0bd2.png">

**Comment by wensonsmith** [comment]
@ZiyunChi 请参加 #85
