### ISSUE TITLE
MacBook 更新到了monterey 之后调用翻译workflow出错，提示以下信息，不知能否修复一下，重度依赖这个flow。

### ISSUE THREAD

**Issue by alexonmr** [wensonsmith/YoudaoTranslate#87]
<img width="264" alt="CleanShot 2021-07-15 at 13 56 50@2x" src="https://user-images.githubusercontent.com/3862430/125737236-598edbca-3eaf-4a0a-b720-cf7e1d67bc4f.png

**Comment by czkboy** [comment]
同，更新完就没法用了

**Comment by wensonsmith** [comment]
@alexonmr 请参考 #85

**Comment by wensonsmith** [comment]
3.0 已发布
