### ISSUE TITLE
有道API迁移的问题

### ISSUE THREAD

**Issue by a367** [wensonsmith/YoudaoTranslate#9]
作者您好！很高兴看到您分享的workflow！
不过最近（2017.06.06），有道似乎关闭了原来的API申请，并将其服务转移到有道智云上了，请问是否要对这个workflow做大的更新？

**Comment by wensonsmith** [comment]
多谢提醒！

我看到公告上写

> 此平台将于 2017-12-31 后停止运行，敬请尽快升级。

所以我会在这两个月前改一下。

- [ ] 更新 API

- [ ] 优化语音发音

- [ ] 添加翻译选中文字的热键

还有啥 ？

**Comment by wujunze** [comment]
嗯嗯  赞👍   我也想提醒作者来着    发现原来已经有小伙伴儿提issues了😀
