### ISSUE TITLE
can't run the workflow on Monterey (macOS 12)

### ISSUE THREAD

**Issue by jisongniu** [wensonsmith/YoudaoTranslate#91]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/35025755/140295931-0c5d3899-f4ea-442b-adbc-9824873addbd.png">

`Reason: launch path not accessible

/usr/bin/php

Check that the selected language exists on your system.

If you're syncing Alfred's preferences, also check that all related workflow files exist locally.

Related Workflow Info...
Name: 'Youdao Translate'
Folder:/Users/jisong/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.fffffff-Fff2F-48fffE-AfffF-fffffffff`

**Comment by superdoliant** [comment]
macOS 12移除了本地的php环境，需要自己手动安装。 https://github.com/shivammathur/homebrew-php

**Comment by wensonsmith** [comment]
#90
