### ISSUE TITLE
Apple Monterey 不支持插件启动

### ISSUE THREAD

**Issue by jqzhangd** [wensonsmith/YoudaoTranslate#92]
MacOS12.0.1 Monterey 不支持插件启动，google发现好像是因为OS删除了PHP，请问有什么办法处理么？
错误提示：Reason: launch path not accessible/usr/bin/php Check that the selected language exists on your system.

![image](https://user-images.githubusercontent.com/30409252/140593381-d87768f2-e572-4350-bdc1-8798a800f5bf.png)

**Comment by wensonsmith** [comment]
Monterey 已经移出了 PHP

正在用 Ts 重构， #90
